/**
 * Land Acquisition (LA) Payment Disbursement Data - Nalgonda District
 * As on 06.09.2026
 * Source: District Collectorate, Nalgonda
 */

const LA_DATA = [
  {
    slNo: 1,
    lao: "SDC Unit-I",
    project: "USBR",
    dtoToken: "2700676998, 07.06.2026",
    creditDate: "28.07.2026",
    releasedCr: 1.88,
    disbursedYesterdayCr: 1.88,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 1.88,
    balanceCr: 0.00,
    totalBeneficiaries: 1,
    beneficiariesPaid: 1,
    balanceBeneficiaries: 0,
    totalExtentAc: 5.00,
    paymentCompletedExtentAc: 5.00,
    balanceExtentAc: 0.00,
    status: "Completed",
    possession: "Completed",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Submerged under UBR. Payment completed.",
    bottleneckCategory: "None"
  },
  {
    slNo: 2,
    lao: "SDC Unit-I",
    project: "Pendlipakala Balancing Reservoir",
    dtoToken: "2522922019, 15.10.2024",
    creditDate: "30.05.2026",
    releasedCr: 11.19,
    disbursedYesterdayCr: 11.19,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 11.19,
    balanceCr: 0.00,
    totalBeneficiaries: 259,
    beneficiariesPaid: 259,
    balanceBeneficiaries: 0,
    totalExtentAc: 51.91,
    paymentCompletedExtentAc: 51.91,
    balanceExtentAc: 0.00,
    status: "Completed",
    possession: "No",
    postAwardCompleted: 0,
    postAwardBalance: 54,
    remarks: "₹27.26 Crores credited, out of which ₹11.19 Crores were disbursed, ₹16.06 Crores transferred to RDO, Devarakonda.",
    bottleneckCategory: "None"
  },
  {
    slNo: 3,
    lao: "SDC Unit-I",
    project: "Pendlipakala Balancing Reservoir",
    dtoToken: "2700673924, 07.06.2026",
    creditDate: "28.07.2026",
    releasedCr: 168.26,
    disbursedYesterdayCr: 113.65,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 113.65,
    balanceCr: 54.61,
    totalBeneficiaries: 1189,
    beneficiariesPaid: 892,
    balanceBeneficiaries: 297,
    totalExtentAc: 814.17,
    paymentCompletedExtentAc: 470.75,
    balanceExtentAc: 343.42,
    status: "In Progress",
    possession: "No",
    postAwardCompleted: 0,
    postAwardBalance: 183,
    remarks: "Active disbursement in progress. 297 beneficiaries and Ac. 343.42 balance extent.",
    bottleneckCategory: "Disbursement in Progress"
  },
  {
    slNo: 4,
    lao: "SDC Unit-II",
    project: "USLIS",
    dtoToken: "2523802411, 28.01.2025",
    creditDate: "30.05.2026",
    releasedCr: 11.00,
    disbursedYesterdayCr: 7.36,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 7.36,
    balanceCr: 3.64,
    totalBeneficiaries: 135,
    beneficiariesPaid: 135,
    balanceBeneficiaries: 0,
    totalExtentAc: 38.32,
    paymentCompletedExtentAc: 38.32,
    balanceExtentAc: 0.00,
    status: "Completed",
    possession: "Completed",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Remaining amount will be used for Wattimarthy Village. After Award passed compensation will be paid.",
    bottleneckCategory: "Surplus Reallocation"
  },
  {
    slNo: 5,
    lao: "SDC Unit-II",
    project: "USLIS (Wattimarthy)",
    dtoToken: "2700677030, 07.06.2026",
    creditDate: "28.07.2026",
    releasedCr: 12.00,
    disbursedYesterdayCr: 0.00,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.00,
    balanceCr: 12.00,
    totalBeneficiaries: 0,
    beneficiariesPaid: 0,
    balanceBeneficiaries: 0,
    totalExtentAc: 33.12,
    paymentCompletedExtentAc: 0.00,
    balanceExtentAc: 33.12,
    status: "Award Pending",
    possession: "No",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Wattimarthy Award to be passed. Villagers requested to pay compensation as per Enhanced Market Value @ Rs. 5,40,000/- instead of Market Value @ Rs. 2,70,000/- at the time of Notification.",
    bottleneckCategory: "Market Value Dispute"
  },
  {
    slNo: 6,
    lao: "SDC Unit-II",
    project: "USLIS (Kondapokoni Gudem & Vanipakala)",
    dtoToken: "2700677054, 07.06.2026",
    creditDate: "28.07.2026",
    releasedCr: 4.00,
    disbursedYesterdayCr: 0.00,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.00,
    balanceCr: 4.00,
    totalBeneficiaries: 0,
    beneficiariesPaid: 0,
    balanceBeneficiaries: 0,
    totalExtentAc: 6.31,
    paymentCompletedExtentAc: 0.00,
    balanceExtentAc: 6.31,
    status: "Enquiry Scheduled",
    possession: "No",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Kondapokoni Gudem & Vanipakala (Ac.6.31 gts) under Award enquiry notices issued. Award enquiry scheduled on 09.09.2026 and 17.09.2026. Villagers requested Enhanced Market Value.",
    bottleneckCategory: "Enquiry Scheduled"
  },
  {
    slNo: 7,
    lao: "SDC Unit-II",
    project: "Dindi Main Canal",
    dtoToken: "2523816396, 31.01.2025",
    creditDate: "28.07.2026",
    releasedCr: 1.00,
    disbursedYesterdayCr: 0.00,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.00,
    balanceCr: 1.00,
    totalBeneficiaries: 0,
    beneficiariesPaid: 0,
    balanceBeneficiaries: 0,
    totalExtentAc: 0.00,
    paymentCompletedExtentAc: 0.00,
    balanceExtentAc: 0.00,
    status: "Completed",
    possession: "N/A",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "No Land Acquisition Payment pending.",
    bottleneckCategory: "None"
  },
  {
    slNo: 8,
    lao: "RDO Miryalaguda",
    project: "Dunnapothula Gandi Lift Irrigation",
    dtoToken: "2700673922, 07.06.2026",
    creditDate: "18.08.2026",
    releasedCr: 3.60,
    disbursedYesterdayCr: 1.26,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 1.26,
    balanceCr: 2.34,
    totalBeneficiaries: 138,
    beneficiariesPaid: 62,
    balanceBeneficiaries: 76,
    totalExtentAc: 36.11,
    paymentCompletedExtentAc: 29.214,
    balanceExtentAc: 6.90,
    status: "In Progress",
    possession: "No",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "₹1,26,86,385 disbursed till today. Most beneficiaries had vivat khbaja issue and title report pending for Govt land survey numbers. Resolving within 15 days.",
    bottleneckCategory: "Title & Survey Dispute"
  },
  {
    slNo: 9,
    lao: "RDO Miryalaguda",
    project: "Nellikal Lift Irrigation",
    dtoToken: "2701729732, 01.08.2026",
    creditDate: "18.08.2026",
    releasedCr: 12.30,
    disbursedYesterdayCr: 0.25,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.25,
    balanceCr: 12.05,
    totalBeneficiaries: 850,
    beneficiariesPaid: 46,
    balanceBeneficiaries: 804,
    totalExtentAc: 45.19,
    paymentCompletedExtentAc: 2.21,
    balanceExtentAc: 42.98,
    status: "In Progress",
    possession: "No",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Total Award amount is ₹3.23 Cr; ₹25,15,000/- disbursed so far. Most beneficiaries had vivat khbaja issue and title report pending for Govt survey numbers. Expected resolution in 20 days.",
    bottleneckCategory: "Title & Survey Dispute"
  },
  {
    slNo: 10,
    lao: "RDO Nalgonda",
    project: "USBR",
    dtoToken: "2700677020, 07.06.2026",
    creditDate: "28.07.2026",
    releasedCr: 5.85,
    disbursedYesterdayCr: 5.85,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 5.85,
    balanceCr: 0.00,
    totalBeneficiaries: 3,
    beneficiariesPaid: 3,
    balanceBeneficiaries: 0,
    totalExtentAc: 12.35,
    paymentCompletedExtentAc: 12.35,
    balanceExtentAc: 0.00,
    status: "Completed",
    possession: "Completed",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "100% disbursement completed for all 3 beneficiaries across 12.35 Acres.",
    bottleneckCategory: "None"
  },
  {
    slNo: 11,
    lao: "RDO Nalgonda",
    project: "USLIS",
    dtoToken: "2700677077, 07.06.2026",
    creditDate: "28.07.2026",
    releasedCr: 5.00,
    disbursedYesterdayCr: 0.00,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.00,
    balanceCr: 5.00,
    totalBeneficiaries: 0,
    beneficiariesPaid: 0,
    balanceBeneficiaries: 0,
    totalExtentAc: 6.10,
    paymentCompletedExtentAc: 0.00,
    balanceExtentAc: 6.10,
    status: "Under SDR Stage",
    possession: "No",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Under SDR stage at Yallareddy Gudem village of Narketpally Mandal (Ac. 6.10 gts).",
    bottleneckCategory: "Statutory Stage"
  },
  {
    slNo: 12,
    lao: "PA to SPL Collector",
    project: "Dindi Main Canal",
    dtoToken: "2523816377, 21.03.2025",
    creditDate: "28.07.2026",
    releasedCr: 6.00,
    disbursedYesterdayCr: 3.53,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 3.53,
    balanceCr: 2.47,
    totalBeneficiaries: 61,
    beneficiariesPaid: 32,
    balanceBeneficiaries: 29,
    totalExtentAc: 58.35,
    paymentCompletedExtentAc: 38.03,
    balanceExtentAc: 20.32,
    status: "In Progress",
    possession: "Partial",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "1. Handed over Ac.23.02 gts in Kistrainipally. 2. Modugula Mallepally: Ac.15.01 gts paid. 3. Ac.5.21 gts roads/vaagu. 4. Balance Ac.9.36 gts requesting enhancement; Ac.5.16 gts title pending (to deposit in LA Authority).",
    bottleneckCategory: "Market Value & Title Dispute"
  },
  {
    slNo: 13,
    lao: "PA to SPL Collector",
    project: "Chinthapally Reservoir",
    dtoToken: "2701729766, 01.08.2026",
    creditDate: "18.08.2026",
    releasedCr: 85.32,
    disbursedYesterdayCr: 2.34,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 2.34,
    balanceCr: 82.98,
    totalBeneficiaries: 737,
    beneficiariesPaid: 21,
    balanceBeneficiaries: 716,
    totalExtentAc: 833.05,
    paymentCompletedExtentAc: 18.32,
    balanceExtentAc: 814.73,
    status: "In Progress",
    possession: "No",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "1. Ac.18.32 gts paid at Chinthapally. 2. Ac.590.04 gts (General Award) Awardees requesting enhanced compensation. 3. Ac.224.09 gts (Consent Award 2018-19) revised proposals submitted to District Collector, Nalgonda.",
    bottleneckCategory: "Major Bottleneck - Rate Revision"
  },
  {
    slNo: 14,
    lao: "RDO Devarakonda",
    project: "Akkampally Reservoir (Lift)",
    dtoToken: "2700673923, 07.06.2026",
    creditDate: "18.08.2026",
    releasedCr: 0.52,
    disbursedYesterdayCr: 0.52,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.52,
    balanceCr: 0.00,
    totalBeneficiaries: 44,
    beneficiariesPaid: 44,
    balanceBeneficiaries: 0,
    totalExtentAc: 4.28,
    paymentCompletedExtentAc: 4.28,
    balanceExtentAc: 0.00,
    status: "Completed",
    possession: "Yes",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Payment 100% completed. Possession successfully handed over to the Irrigation Department.",
    bottleneckCategory: "None"
  },
  {
    slNo: 15,
    lao: "RDO Devarakonda",
    project: "Ambabhavani Lift Irrigation",
    dtoToken: "2523500831, 18.12.2024",
    creditDate: "28.07.2026",
    releasedCr: 0.32,
    disbursedYesterdayCr: 0.32,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.32,
    balanceCr: 0.00,
    totalBeneficiaries: 35,
    beneficiariesPaid: 35,
    balanceBeneficiaries: 0,
    totalExtentAc: 4.11,
    paymentCompletedExtentAc: 4.11,
    balanceExtentAc: 0.00,
    status: "Completed",
    possession: "Yes",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Payment 100% completed. Possession successfully handed over to the Irrigation Department.",
    bottleneckCategory: "None"
  },
  {
    slNo: 16,
    lao: "RDO Devarakonda",
    project: "Pendlipakala Balancing Reservoir (R&R Centre)",
    dtoToken: "2522922019, 15.10.2024",
    creditDate: "30.05.2026",
    releasedCr: 16.03,
    disbursedYesterdayCr: 10.95,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 10.95,
    balanceCr: 5.08,
    totalBeneficiaries: 51,
    beneficiariesPaid: 29,
    balanceBeneficiaries: 22,
    totalExtentAc: 79.07,
    paymentCompletedExtentAc: 39.25,
    balanceExtentAc: 39.82,
    status: "In Progress",
    possession: "In Process",
    postAwardCompleted: 47,
    postAwardBalance: null,
    remarks: "Gummadavelly Village awardees not willing to receive compensation due to alignment issue.",
    bottleneckCategory: "Alignment Dispute"
  },
  {
    slNo: 17,
    lao: "RDO Devarakonda",
    project: "Kistrainpally Balancing Reservoir",
    dtoToken: "2523802442, 28.01.2025",
    creditDate: "28.07.2026",
    releasedCr: 3.18,
    disbursedYesterdayCr: 0.00,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 0.00,
    balanceCr: 3.18,
    totalBeneficiaries: 18,
    beneficiariesPaid: 0,
    balanceBeneficiaries: 18,
    totalExtentAc: 26.00,
    paymentCompletedExtentAc: 0.00,
    balanceExtentAc: 26.00,
    status: "In Progress",
    possession: "No",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "Awardees not willing to take compensation. Requesting to enhance compensation amount in view of market value revision.",
    bottleneckCategory: "Market Value Dispute"
  },
  {
    slNo: 18,
    lao: "RDO Devarakonda",
    project: "Shivannagudem Balancing Reservoir",
    dtoToken: "2701729737, 01.08.2026",
    creditDate: "18.08.2026",
    releasedCr: 15.50,
    disbursedYesterdayCr: 12.08,
    disbursedTodayCr: 0.00,
    totalDisbursedCr: 12.08,
    balanceCr: 3.42,
    totalBeneficiaries: 22,
    beneficiariesPaid: 18,
    balanceBeneficiaries: 4,
    totalExtentAc: 54.23,
    paymentCompletedExtentAc: 43.23,
    balanceExtentAc: 11.00,
    status: "In Progress",
    possession: "Partial",
    postAwardCompleted: null,
    postAwardBalance: null,
    remarks: "District Collector, Nalgonda conducted village meeting with Hon'ble MLA Devarakonda; convinced awardees. Payments under active process.",
    bottleneckCategory: "Resolved via Collector Meeting"
  }
];

const BOTTLENECK_HIGHLIGHTS = [
  {
    title: "Chinthapally Reservoir (₹82.98 Cr Pending)",
    lao: "PA to SPL Collector",
    urgency: "high",
    amount: "₹82.98 Cr",
    extent: "814.73 Ac",
    beneficiaries: "716 Pending",
    description: "Ac. 590.04 gts (General Award) awardees refusing compensation demanding higher rates. Ac. 224.09 gts consent award revised proposal submitted to District Collector.",
    actionItem: "Expedite Collectorate approval on revised consent proposals; hold stakeholder negotiation meeting."
  },
  {
    title: "Pendlipakala Balancing Reservoir (₹54.61 Cr Pending)",
    lao: "SDC Unit-I",
    urgency: "high",
    amount: "₹54.61 Cr",
    extent: "343.42 Ac",
    beneficiaries: "297 Pending",
    description: "Substantial funds remaining for 297 beneficiaries across Ac. 343.42. ₹113.65 Cr disbursed so far.",
    actionItem: "Accelerate verification camps and DTO clearance for remaining 297 awardees."
  },
  {
    title: "Nellikal & Dunnapothula Gandi (Title & Survey Disputes)",
    lao: "RDO Miryalaguda",
    urgency: "medium",
    amount: "₹14.39 Cr",
    extent: "49.88 Ac",
    beneficiaries: "880 Pending",
    description: "880 beneficiaries delayed due to vivat khbaja issues and pending title reports on Government land survey numbers.",
    actionItem: "Revenue and Survey team target completion in 15-20 days SLA."
  },
  {
    title: "Wattimarthy Village Rate Enhancement Claim",
    lao: "SDC Unit-II",
    urgency: "medium",
    amount: "₹12.00 Cr",
    extent: "33.12 Ac",
    beneficiaries: "Award Pending",
    description: "Villagers demanding compensation at ₹5,40,000/acre vs preliminary notification value of ₹2,70,000/acre.",
    actionItem: "Negotiation committee review on prevailing guideline values."
  },
  {
    title: "Gummadavelly Village R&R Alignment Dispute",
    lao: "RDO Devarakonda",
    urgency: "medium",
    amount: "₹5.08 Cr",
    extent: "39.82 Ac",
    beneficiaries: "22 Pending",
    description: "Awardees resisting compensation due to disagreement over the R&R Centre site alignment.",
    actionItem: "Joint inspection by Irrigation and Revenue authorities with local representatives."
  },
  {
    title: "Shivannagudem Reservoir - Successful Intervention",
    lao: "RDO Devarakonda",
    urgency: "success",
    amount: "₹12.08 Cr Paid",
    extent: "43.23 Ac",
    beneficiaries: "18/22 Paid",
    description: "Meeting conducted by District Collector with Hon'ble MLA Devarakonda successfully convinced awardees; 78% disbursed.",
    actionItem: "Clear final 4 claims (₹3.42 Cr) to complete project."
  }
];
